In [3]:
import numpy as np

In [5]:
arr=np.array([4,5,12,90,76])
print(arr)
print(arr.dtype)
print(arr.size)
print(arr.shape)
print(arr.ndim)

[ 4  5 12 90 76]
int64
5
(5,)
1


In [9]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(np.dtype)
print(np.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.dtype'>
<function ndim at 0x000002D47E77D7A0>
(2, 3)


In [8]:
arr=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [10]:
arr=np.array([23,45,90,30,20])
print(arr)

[23 45 90 30 20]


In [11]:
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
arr=np.arange(3,20)
print(arr)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [14]:
arr=np.linspace(1,100,10)
print(arr)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [15]:
arr=np.arange(50,101)
print(arr)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [16]:
arr=np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [18]:
arr=np.arange(2,100,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [19]:
arr=np.arange(2,100,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [20]:
arr=np.arange(1,100,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [21]:
arr=np.linspace(1,10,20)
print(arr)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [23]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [24]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
arr=np.zeros((2,3,4))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [27]:
arr=np.zeros((4,4))
print(arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
arr=np.zeros((2,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
arr=np.ones((2,3,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [31]:
arr=np.ones((5,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
arr=np.ones((2,2,2))
print(arr)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [33]:
arr=np.random.rand(5)
print(arr)

[0.55335221 0.57929382 0.73028664 0.14983233 0.72477178]


In [34]:
arr=np.random.randint(1,100,10)
print(arr)

[21 95 92 21 13  6 24 34 69 35]


In [35]:
arr=np.random.choice([10,20,30,40],5)
print(arr)

[40 40 40 10 30]


In [36]:
arr=np.random.randint(1,100,15)
print(arr)

[24 66 79 66 20 18 82 97 73 39  4 43 57 48 45]


In [37]:
arr=np.random.rand(5)
print(arr)

[0.60341056 0.86415314 0.31177142 0.91747072 0.25251506]


In [39]:
arr=np.random.rand(4,4)
print(arr)

[[0.44484295 0.9643333  0.50597602 0.87126139]
 [0.09792294 0.0285847  0.19521718 0.7897952 ]
 [0.24767247 0.3472559  0.8164269  0.06944792]
 [0.3117961  0.8685835  0.21272829 0.78696794]]


In [40]:
arr=np.arange(24)
print(arr.reshape(2,3,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [41]:
arr=np.arange(36)
print(arr.reshape(6,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [42]:
arr=np.arange(20)
print(arr.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [43]:
arr=np.arange(18)
print(arr.reshape(3,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [44]:
arr=np.arange(27)
print(arr.reshape(3,3,3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [46]:
arr=np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [48]:
arr=np.arange(16).reshape(4,4)
print(arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [50]:
arr=np.arange(25).reshape(5,5)
print(arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [51]:
arr=np.arange(27).reshape(3,3,3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [52]:
arr=np.array([10,20,30,40,50])
print(arr[0])

10


In [53]:
arr=np.array([[10,20],[30,40]])
print(arr[0,1])
print(arr[1,0])

20
30


In [55]:
arr=np.arange(27).reshape(3,3,3)
print(arr)
print(arr[1,2,0])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
15


In [56]:
arr = np.arange(10)

print(arr[2:7])

[2 3 4 5 6]


In [57]:
arr=np.arange(20)
print(arr[::2])

[ 0  2  4  6  8 10 12 14 16 18]


In [58]:
arr=np.arange(20)
print(arr[::-1])

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [59]:
arr=np.arange(20)
print(arr[:10:-1])

[19 18 17 16 15 14 13 12 11]


In [61]:
arr=np.arange(16).reshape(4,4)
print(arr[1:3,1:3])

[[ 5  6]
 [ 9 10]]


In [62]:
arr=np.arange(20)
print(arr[:-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [63]:
arr=np.array([10,13,45,90])
print(arr[arr>20])

[45 90]


In [64]:
arr=np.arange(20)
print(arr[arr%2==0])

[ 0  2  4  6  8 10 12 14 16 18]


In [65]:
arr=np.random.randint(1,100,20)
print(arr)
print(arr[arr>50])

[90 79 64 91 63 89 52 23 97 19 77 72 81 71 89  7 45 18 36 13]
[90 79 64 91 63 89 52 97 77 72 81 71 89]


In [67]:
arr=np.array([90,43,89,40,56,77])
print(arr[(arr>10) &(arr<200)])

[90 43 89 40 56 77]


In [68]:
arr=np.arange(100)
print(arr[arr%2!=0])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [69]:
arr=np.arange(100)
print(arr[arr%5==0])

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [70]:
arr=np.array([1,2,3])
print(arr+10)

[11 12 13]


In [75]:
arr=np.array([[1,2],[3,4]])
print(arr*5)

[[ 5 10]
 [15 20]]


In [76]:
arr=np.arange(9).reshape(3,3)
print(arr+np.array([1,2,3]))

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [80]:
arr=np.arange(1,10).reshape(3,3)
print(arr+100)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [81]:
arr=np.arange(1,10).reshape(3,3)
print(arr*3)
print(arr/2)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [82]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [91]:
a=np.array([3,4,5])
b=np.array([9,8,7])
print(a+b)
print(np.square(a))
print(np.sqrt(b))
print(a-b)
print(np.log(a))
print(np.sin(a))
print(np.tan(a))
print(np.cos(a))
print(a*a*a)
print(np.exp(a))

[12 12 12]
[ 9 16 25]
[3.         2.82842712 2.64575131]
[-6 -4 -2]
[1.09861229 1.38629436 1.60943791]
[ 0.14112001 -0.7568025  -0.95892427]
[-0.14254654  1.15782128 -3.38051501]
[-0.9899925  -0.65364362  0.28366219]
[ 27  64 125]
[ 20.08553692  54.59815003 148.4131591 ]


In [95]:
arr=np.array([10,20,30])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.var(arr))
print(np.prod(arr))
print(np.cumsum(arr))

60
30
10
66.66666666666667
6000
[10 30 60]


In [96]:
arr=np.array([[10,20,30],
              [40,50,60]])
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

210
[50 70 90]
[ 60 150]


In [106]:
arr=np.arange(1,26).reshape(5,5)
print(arr)
even=(arr[arr%2==0])=0
print(even)
print(arr[:,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
0
[ 0  7  0 17  0]


In [105]:
arr=np.arange(1,26).reshape(5,5)
print(arr)
print(arr[1:4,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [110]:
arr=np.arange(1,26).reshape(5,5)
print(arr)
a_even=arr.copy()
a_even[a_even%2==0]=0
print(even)
print(arr[arr>15])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
0
[16 17 18 19 20 21 22 23 24 25]


In [111]:
arr=np.arange(1,26).reshape(5,5)
print(arr+100)

[[101 102 103 104 105]
 [106 107 108 109 110]
 [111 112 113 114 115]
 [116 117 118 119 120]
 [121 122 123 124 125]]


In [112]:
arr=np.arange(1,26).reshape(5,5)
print(arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [113]:
arr=np.arange(1,26).reshape(5,5)
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

325
13.0
7.211102550927978
52.0
1
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210 231 253 276 300 325]
[                   1                    2                    6
                   24                  120                  720
                 5040                40320               362880
              3628800             39916800            479001600
           6227020800          87178291200        1307674368000
       20922789888000      355687428096000     6402373705728000
   121645100408832000  2432902008176640000 -4249290049419214848
 -1250660718674968576  8128291617894825984 -7835185981329244160
  7034535277573963776]
